adaptation for use of Thunar scripts in PCManFM

diff --git a/Thunar_Scripts/Convert_Image/img2pdf b/Thunar_Scripts/Convert_Image/img2pdf
--- a/Thunar_Scripts/Convert_Image/img2pdf
+++ b/Thunar_Scripts/Convert_Image/img2pdf
@@ -1,28 +1,39 @@
 #!/bin/bash
 # Converte arquivo imagem para PDF
 # Requer Zenity e ImageMagick
+# 2019
 
 # argumentos de entrada
-arg="$@"        
-elements="$#"
-
+arg="$@"
+script=$(basename $0)
 today=$(date +%Y-%m-%d)
-ext_array=("PNG" "png" "JPG" "jpg" "svg" "SVG")
-
-# Confirmando ação
-gdialog --title "Script" --center --stdout --yesno \
-"Execute: img2pdf" \
-100 100
-
-# Escrevendo arquivo de log
-echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-img2pdf-$today"
 
 # Checar argumento
 if [[ "$arg" = "" ]]; then
-    echo "Empty argument!" >> /tmp/"log-img2pdf-$today"
-    gdialog --msgbox "Select Files!"
+    echo "Empty argument!" >> /tmp/"log-$script-$today"
+    zenity --info --text="Select Files!"
     exit 0
 fi
+
+# detalhes iniciais
+elements="$#"
+local=$(dirname $1)
+ext_array=("PNG" "png" "JPG" "jpg" "svg" "SVG")
+
+# Confirmando ação
+zenity --question \
+--title="Script" \
+--text="Execute: $script" \
+--ok-label="Yes" \
+--cancel-label="No"
+temp=$?
+
+if [[ $temp -eq 1 ]]; then
+      exit 0
+fi
+
+# Escrevendo arquivo de log
+echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"
 
 # Percorrendo os argumentos de entrada
 temp=""
@@ -44,7 +55,7 @@ do
     name="PDF"  # padrão para mais de um arquivo
     for ext in ${ext_array[@]}; do
         if [[ $ext_temp == ".$ext" ]]; then
-            echo "Image file: $arg OK" >> /tmp/"log-img2pdf-$today"
+            echo "Image file: $arg OK" >> /tmp/"log-$script-$today"
             temp="$temp $arg"
             # nome do arquivo
             if [[ $elements -eq 1 ]]; then
@@ -54,7 +65,7 @@ do
                         break;
                     fi
                 done
-                name="${arg:count + 1:last - count - 1}" 
+                name="${arg:count + 1:last - count - 1}"
             fi
             break
         fi
@@ -62,15 +73,16 @@ do
 done
 
 # Inserir Data
-output="$name-$(date '+%Y-%m-%d_%H:%M:%S').pdf"
+output="$local/$name-$(date '+%Y-%m-%d_%H:%M:%S').pdf"
 if [[ -f $output ]]; then
-    echo "Error: '$output' already exists!" >> /tmp/"log-img2pdf-$today"
-    gdialog --msgbox "Error: '$output' already exists!"
+    echo "Error: '$output' already exists!" >> /tmp/"log-$script-$today"
+    zenity --error --text="Error: '$output' already exists!"
 else
-    echo "Converting..." >> /tmp/"log-img2pdf-$today"
+    echo "Converting..." >> /tmp/"log-$script-$today"
+    # zenity --info --text="convert $temp $output"
     $(convert $temp $output)
-    echo "Output: $output" >> /tmp/"log-img2pdf-$today"
+    echo "Output: $output" >> /tmp/"log-$script-$today"
 fi
 
-echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-img2pdf-$today"
+echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
 exit 0
diff --git a/Thunar_Scripts/Convert_Image/png2jpg b/Thunar_Scripts/Convert_Image/png2jpg
--- a/Thunar_Scripts/Convert_Image/png2jpg
+++ b/Thunar_Scripts/Convert_Image/png2jpg
@@ -1,35 +1,46 @@
 #!/bin/bash
 # Converte arquivo imagem PNG para JPG
 # Requer Zenity e ImageMagick
+# 2019
 
-arg="$@"    # argumentos de entrada
+# argumentos de entrada
+arg="$@"
+script=$(basename $0)
 today=$(date +%Y-%m-%d)
-ext_original=".PNG"
-
-# gdialog --title "Script" --center --stdout --yesno \
-# "Execute: png2jpg" \
-# 100 100
-
-# if [[ "$?" != "0" ]]; then
-#       exit 0
-# fi
-
-# Escrevendo arquivo de log
-echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-png2jpg-$today"
 
 # Checar argumento
 if [[ "$arg" = "" ]]; then
-    echo "Empty argument!" >> /tmp/"log-png2jpg-$today"
-    gdialog --msgbox "Select Files!"
+    echo "Empty argument!" >> /tmp/"log-$script-$today"
+    zenity --info --text="Select Files!"
     exit 0
 fi
+
+# detalhes iniciais
+ext_original=(".PNG")
+ext_output="jpg"
+extra="-quality 90"
+
+# Confirmando ação
+zenity --question \
+--title="Script" \
+--text="Execute: $script" \
+--ok-label="Yes" \
+--cancel-label="No"
+temp=$?
+
+if [[ $temp -eq 1 ]]; then
+      exit 0
+fi
+
+# Escrevendo arquivo de log
+echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"
 
 # Percorrendo os argumentos de entrada
 for arg
 do
     size=${#arg}
     count=$size
-    echo "Renaming: $arg" >> /tmp/"log-png2jpg-$today"
+    echo "Convert: $arg" >> /tmp/"log-$script-$today"
 
     # Procurando extensão
     while [[ $count -ge 0 ]]; do
@@ -40,39 +51,42 @@ do
 
     # Checar extensão
     ext_temp=$(echo "${arg:count:size - count}" | tr '[:lower:]' '[:upper:]')
-    echo "Image file: " >> /tmp/"log-png2jpg-$today"
-    if [[ $ext_temp != $ext_original ]]; then
-        echo "Invalid image file!" >> /tmp/"log-png2jpg-$today"
-        gdialog --msgbox "Invalid image file!"
-        exit 0
+    if [[ $ext_temp != ${ext_original[0]} && $ext_temp != ${ext_original[1]} ]]; then
+        echo "Invalid image file!" >> /tmp/"log-$script-$today"
+        zenity --error --text="Invalid image file!"        
+        continue
     fi
 
     # Inserir Data
-    temp="${arg:0:$count}.jpg"
+    temp="${arg:0:$count}.$ext_output"
     if [[ -f $temp ]]; then
-        echo "Error: '$temp' already exists!" >> /tmp/"log-png2jpg-$today"
-        gdialog --msgbox "Error: '$temp' already exists!"
+        echo "Error: '$temp' already exists!" >> /tmp/"log-$script-$today"
+        zenity --error --text="Error: '$temp' already exists!"
     else
-        echo "Converting..." >> /tmp/"log-png2jpg-$today"
-        $(convert "$arg" "$temp")
-        echo "New: $temp" >> /tmp/"log-png2jpg-$today"
+        echo "Converting..." >> /tmp/"log-$script-$today"
+        # zenity --info --text="convert $arg $extra $temp"
+        $(convert "$arg" $extra "$temp")
+        echo "New: $temp" >> /tmp/"log-$script-$today"
     fi
 done
 
-gdialog --title "Remove" --center --stdout --yesno \
-"Remove original files (y/n)?" \
-0 0
-
-if [[ "$?" = "1" ]]; then
-      exit 0
-fi
-
 # Remover arquivos
-for arg
-do
-    echo "Removing: $arg" >> /tmp/"log-png2jpg-$today"
-    rm "$arg"
-done
+# zenity --question \
+# --title="Remove" \
+# --text="Remove original files?" \
+# --ok-label="Yes" \
+# --cancel-label="No"
+# temp=$?
 
-echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-png2jpg-$today"
+# if [[ $temp -eq 1 ]]; then
+#       exit 0
+# fi
+
+# for arg
+# do
+#     echo "Removing: $arg" >> /tmp/"log-$script-$today"
+#     rm "$arg"
+# done
+
+echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
 exit 0
diff --git a/Thunar_Scripts/Convert_Image/svg2png b/Thunar_Scripts/Convert_Image/svg2png
--- a/Thunar_Scripts/Convert_Image/svg2png
+++ b/Thunar_Scripts/Convert_Image/svg2png
@@ -1,35 +1,46 @@
 #!/bin/bash
 # Converte arquivo imagem SVG para PNG
-# Requer Zenity e Inkscape
+# Requer Zenity e ImageMagick
+# 2019
 
-arg="$@"    # argumentos de entrada
+# argumentos de entrada
+arg="$@"
+script=$(basename $0)
 today=$(date +%Y-%m-%d)
-ext_original=".SVG"
-
-# gdialog --title "Script" --center --stdout --yesno \
-# "Execute: svg2png" \
-# 100 100
-
-# if [[ "$?" != "0" ]]; then
-#       exit 0
-# fi
-
-# Escrevendo arquivo de log
-echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-svg2png-$today"
 
 # Checar argumento
 if [[ "$arg" = "" ]]; then
-    echo "Empty argument!" >> /tmp/"log-svg2png-$today"
-    gdialog --msgbox "Select Files!"
+    echo "Empty argument!" >> /tmp/"log-$script-$today"
+    zenity --info --text="Select Files!"
     exit 0
 fi
+
+# detalhes iniciais
+ext_original=(".SVG")
+ext_output="png"
+extra=""
+
+# Confirmando ação
+zenity --question \
+--title="Script" \
+--text="Execute: $script" \
+--ok-label="Yes" \
+--cancel-label="No"
+temp=$?
+
+if [[ $temp -eq 1 ]]; then
+      exit 0
+fi
+
+# Escrevendo arquivo de log
+echo "Started [ $(date '+%Y-%m-%d %H:%M:%S') ]." > /tmp/"log-$script-$today"
 
 # Percorrendo os argumentos de entrada
 for arg
 do
     size=${#arg}
     count=$size
-    echo "Convert: $arg" >> /tmp/"log-svg2png-$today"
+    echo "Convert: $arg" >> /tmp/"log-$script-$today"
 
     # Procurando extensão
     while [[ $count -ge 0 ]]; do
@@ -40,38 +51,42 @@ do
 
     # Checar extensão
     ext_temp=$(echo "${arg:count:size - count}" | tr '[:lower:]' '[:upper:]')
-    if [[ $ext_temp != $ext_original ]]; then
-        echo "Invalid image file!" >> /tmp/"log-svg2png-$today"
-        gdialog --msgbox "Invalid image file!"
+    if [[ $ext_temp != ${ext_original[0]} && $ext_temp != ${ext_original[1]} ]]; then
+        echo "Invalid image file!" >> /tmp/"log-$script-$today"
+        zenity --error --text="Invalid image file!"        
         continue
     fi
 
     # Inserir Data
-    temp="${arg:0:$count}.png"
+    temp="${arg:0:$count}.$ext_output"
     if [[ -f $temp ]]; then
-        echo "Error: '$temp' already exists!" >> /tmp/"log-svg2png-$today"
-        gdialog --msgbox "Error: '$temp' already exists!"
+        echo "Error: '$temp' already exists!" >> /tmp/"log-$script-$today"
+        zenity --error --text="Error: '$temp' already exists!"
     else
-        echo "Converting..." >> /tmp/"log-svg2png-$today"
+        echo "Converting..." >> /tmp/"log-$script-$today"
+        # zenity --info --text="inkscape -z $arg --export-png=$temp"
         $(inkscape -z "$arg" --export-png="$temp")
-        echo "New: $temp" >> /tmp/"log-svg2png-$today"
+        echo "New: $temp" >> /tmp/"log-$script-$today"
     fi
 done
 
-# gdialog --title "Remove" --center --stdout --yesno \
-# "Remove original files (y/n)?" \
-# 0 0
+# Remover arquivos
+# zenity --question \
+# --title="Remove" \
+# --text="Remove original files?" \
+# --ok-label="Yes" \
+# --cancel-label="No"
+# temp=$?
 
-# if [[ "$?" = "1" ]]; then
+# if [[ $temp -eq 1 ]]; then
 #       exit 0
 # fi
 
-# # Remover arquivos
 # for arg
 # do
-#     echo "Removing: $arg" >> /tmp/"log-svg2png-$today"
+#     echo "Removing: $arg" >> /tmp/"log-$script-$today"
 #     rm "$arg"
 # done
 
-echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-svg2png-$today"
+echo "Finished [ $(date '+%Y-%m-%d %H:%M:%S') ]." >> /tmp/"log-$script-$today"
 exit 0
